### ISSUE TITLE
Create the Home / Landing Page of the site

### ISSUE THREAD

**Issue by Aryan-Kumar-Thakur** [gdsc-jssstu/Programming_Community#1]
Create the Home page of programming community site using basic HTML, CSS and JavaScript which contains a basic introduction about programming community and cards containing informations about other pages with visit link.

You can use any dummy image in the image tag or places where image is required for now.

The files for the Home pages are index.html for CSS use index.css and for JavaScript use index.js.

Request to assign the issue to avoid any conflict.

**Comment by Prithwi32** [comment]
@Aryan-Kumar-Thakur please could you assign this task to me

**Comment by Aryan-Kumar-Thakur** [comment]
> @Aryan-Kumar-Thakur please could you assign this task to me

sure, @Prithwi32 . I assign this to you. Feel free to make a PR when you are done with your work. All the best 👍

**Comment by Prithwi32** [comment]
> > @Aryan-Kumar-Thakur please could you assign this task to me
> 
> sure, @Prithwi32 . I assign this to you. Feel free to make a PR when you are done with your work. All the best 👍

Hey could could you review my PR and suggest me

**Comment by Aryan-Kumar-Thakur** [comment]
> @Aryan-Kumar-Thakur Hey please could you review my PR and suggest me

Hey, sorry for the delay. we would like to inform you that we merge your PR. Thank you for your contribution. we are looking forward for more contribution from your side. Have a nice day !!.

**Comment by Prithwi32** [comment]
> > @Aryan-Kumar-Thakur Hey please could you review my PR and suggest me
> 
> Hey, sorry for the delay. we would like to inform you that we merge your PR. Thank you for your contribution. we are looking forward for more contribution from your side. Have a nice day !!.

@Aryan-Kumar-Thakur 
Sure :)
Thank you.. you made my day!
